config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :keywords, only: [:create, :update, :destroy]
  end
  resources :products
  resources :stores

  root 'welcome#index'
end

app/models/keyword.rb
class Keyword < ApplicationRecord
    # validates :name, presence: true
    validates :name,
                presence: true,
                uniqueness: {
                    alert: "You are trying to enter a keyword that already exists."
                }

    belongs_to :category
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :update, :destroy]
  before_action :set_category
  before_action :set_keyword, only: [:update, :destroy]
  

  # POST /keywords or /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)
    @keyword.category = @category
    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword.category, notice: "Keyword was successfully created." }
        # format.json { render :show, status: :created, location: @keyword.category }
      else
        format.html { render :new, status: :unprocessable_entity, alert: "You are trying to enter a keyword that already exists." }
        # format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1 or /keywords/1.json
  def update
    # @category = Category.find(params[:category_id])
    # @keyword = Keyword.find(params[:id])

    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword.category, notice: "Keyword was successfully updated." }
        # format.json { render :show, status: :ok, location: @keyword.category }
      else
        format.html { render :edit, status: :unprocessable_entity, alert: "You are trying to enter a keyword that already exists." }
        # format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1 or /keywords/1.json
  def destroy
    # @category = Category.find(params[:category_id])
    # @keyword = Keyword.find(params[:id])

    title = @keyword.name

    @keyword.destroy

    respond_to do |format|
      if @keyword.destroy
        format.html { redirect_to @keyword.category, notice: "The keyword \"#{title}\" was deleted successfully." }
        format.json { render :show, status: :ok, location: @keyword.category }
      else
        format.html { render :new, status: :unprocessable_entity, alert: "There was an error deleting the keyword." }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end
    
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyword_params
      params.require(:keyword).permit(:name)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<!--<div class="form-title">
    <div class="row">
        <div class="col-sm-6">
            <h1><%#= name %> <b>Keyword</b></h1>
        </div>
    </div>
</div>-->

<%= form_for([@category,@keyword], remote: true, html: {id: "keywords-form"}) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @keyword.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-md-2">
      <%#= f.label "Name" %>
      <%= f.text_field :name, autofocus: true, placeholder: "Name", class:"form-control" %>
    </div>

    <div class="col-md-2">
      <%= f.submit "New Keyword", class:"btn btn-success" %>
    </div>
  </div>
  
  <%#= link_to "Back", keywords_path, class:"btn btn-outline-primary" %>
<% end %>

app/views/keywords/edit.html.erb
<div class="container-xl">
    <div class="table-wrapper">
        <%= render "form", name:"Add" %>
    </div>
</div>

app/views/keywords/index.html.erb
<div class="container-xl">
  <div class="table-responsive">
    <div class="table-wrapper">
      <div class="table-title">
        <div class="row">
          <div class="col-sm-6">
            <h2>Manage <b>Keywords</b></h2>
          </div>
        </div>
      </div>

      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @keywords.each do |keyword| %>
          <tr>
            <td><%= keyword.name %></td>
            <td>
              
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/keywords/new.html.erb
<div class="container-xl">
    <div class="table-wrapper">
        <%= render "form", name:"Add" %>
    </div>
</div>

app/views/keywords/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @keyword.name %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>