config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :keywords, only: [:create, :update, :destroy]
  end
  resources :products
  resources :stores

  root 'welcome#index'
end

app/models/category.rb
class Category < ApplicationRecord
    # validates :name, presence: true
    has_many :keywords
    # belongs_to :product

    validates :name,
                presence: true,
                uniqueness: {
                    message: ->(object, data) do
                        "#{object.name} is already taken."
                    end
                }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.order(:name)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @keyword = Keyword.new
  end

  # GET /categories/new
  def new
    @category = Category.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity, notice: "There was an error creating the category." }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    category_name = @category.name
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "The category \"#{category_name}\"ategory was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity, notice: "There was an error updating the category." }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    # @keywords = Keyword.where(category_id: params[:id])
    # raise @keywords.to_yaml
    Keyword.destroy_by(category_id: params[:id])#delete_all/destroy_all

    category_name = @category.name

    @category.destroy
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_url, notice: "The category \"#{category_name}\" was successfully destroyed." }
        # format.json { head :no_content }
      else
        format.html { render categories_url, status: :unprocessable_entity, notice: "There was an error deleting the category." }
      end
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end
    
    def category_params
      params.require(:category).permit(:name)
    end
  end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="form-title">
    <div class="row">
        <div class="col-sm-6">
            <h1><%= name %> <b>Category</b></h1>
        </div>
    </div>
</div>

<%= form_for(@category, remote: true) do |f| %>
    <% @category.errors.full_messages.each do |message| %>
        <div class="be-red white">
            *<%= message %>
        </div>
    <%end%>

    <div class="form-group row">
        <div class="col-md-4">
            <%= f.label "Name", class:"control-label" %>
            <%= f.text_field :name, autofocus: true, class:"form-control" %>
        </div>
    </div>

    <div class="padding_top25">
        <%= f.submit "Save", class:"btn btn-success" %>
        <%= link_to "Back", categories_path, class:"btn btn-outline-primary" %>
    </div>
<%end%>

app/views/categories/edit.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <%= render "form", name:"Edit" %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container-xl">
  <div class="table-responsive">
    <div class="table-wrapper">
      <%= render "partials/table_title", entity_label: "Categories", button_label: "Category" %>

      <table class="table table-striped table-hover table-category">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td>
                <%= link_to category, class:"btn btn-primary" do %>
                    <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-binoculars" viewBox="0 0 16 16">
                      <path d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z"/>
                    </svg> %>
                    Show
                <% end %>
                <%= link_to edit_category_path(category), class:"btn btn-success" do %>
                    <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                      <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
                    </svg> %>
                    Edit
                <% end %>
                <%= link_to category, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure you want to delete this category?' } do %>
                    <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                      <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                    </svg> %>
                    Delete
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <%= render "form", name:"Add" %>
        </div>
    </div>
</div>

app/views/categories/new.js.erb
console.log("Ingresó al modal");


app/views/categories/show.html.erb
<div class="container-xl">
  <div class="table-responsive">
    <div class="table-wrapper">
      <h3>Category: <b><%= @category.name %></b></h3>

      <div>
        <strong>Manage Keywords</strong>
        <%= render "keywords/form" %>
        
        <% if @category.keywords.count > 0 %>
        <div class="container border bg-light">
          <div class="row">
            <% @category.keywords.order(:name).each do |keyword| %>
            <div class="col-md-4 p-3">
              <%= keyword.name %>
              <%= link_to "Delete", [@category, keyword], remote: true, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure you want to delete this keyword?' } %>
            </div>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>

      <div class="padding_top25">
        <%#= link_to "Edit", edit_category_path(@category), class:"btn btn-success" %>
        <%= link_to "Back", categories_path, class:"btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>