config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :keywords, only: [:create, :update, :destroy]
  end
  resources :products
  resources :stores

  root 'welcome#index'
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :color, presence: true
    # validates :category, presence: true
    validates :size, presence: true
    validates :price, presence: true
    # validates :size, numericality: { message: "%{value} seems wrong" }

    # has_many :stores
    belongs_to :category

    has_many :store_products
    # has_many :stores, :through => :store_product
    has_many :stores, through: :store_products

    after_create :save_stores
    after_update :update_stores

    def category_name
        category.try(:name)
    end

    def category_name=(name)
        self.category = Category.find_or_create_by_name(name) if name.present?
    end

    def stores=(value)
        @stores = value
    end

    def save_stores
        if @stores != nil
            @stores.each do |id|
                StoreProduct.create(store_id: id, product_id: self.id)
            end
        end
    end

    def update_stores
        StoreProduct.destroy_by(product_id: self.id)#delete_all/destroy_all
        if @stores != nil
            @stores.each do |id|
                StoreProduct.create(store_id: id, product_id: self.id)
            end
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_store_product_store_id, only: [:edit]

  # GET /products or /products.json
  def index
    @products = Product.order(:name)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @stores = Store.order(:name)
    
    # @store_product = @product.store_products.build
  end

  # GET /products/1/edit
  def edit
    @categories = Category.order(:name)
    @stores = Store.order(:name)

    # category_id = @Product.category_id
    # @category_name = Category.find(category_id)
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.stores = params[:stores]

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: "Product was successfully created." }
        format.json { render :new, status: :created, location: products_path }
      else
        format.html { render :new, status: :unprocessable_entity, alert: "There was an error creating the product." }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    product_name = @product.name
    @product.stores = params[:stores]

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: "The product \"#{product_name}\" was successfully updated." }
        # format.json { render :edit, status: :ok, location: products_path }
      else
        format.html { render :edit, status: :unprocessable_entity, notice: "There was an error updating the product." }
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    product_name = @product.name
    StoreProduct.destroy_by(product_id: params[:id])#delete_all/destroy_all
    @product.destroy
    respond_to do |format|
      if @product.destroy
        format.html { redirect_to products_url, notice: "The store \"#{product_name}\" was successfully deleted." }
      else
        format.html { render stores_path, status: :unprocessable_entity, notice: "There was an error deleting the product." }
      end
    end
  end

  private
  def set_store_product_store_id
      @store_product = StoreProduct.select(:store_id).where(product_id: params[:id])
  end

    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :color, :category_id, :size, :price, :stores)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="form-title">
    <div class="row">
        <div class="col-sm-6">
            <h1><%= name %> <b>Product</b></h1>
        </div>
    </div>
</div>

<%= form_for(@product, remote: true, class:"needs-validation") do |f| %>
    <% if @product.category_id != nil && @product.category != nil %>
    <% category_name = @product.category.name %>
    <% elsif %>
    <% category_name = "" %>
    <% end %>

    <% @product.errors.full_messages.each do |message| %>
        <div class="be-red white">
            *<%= message %>
        </div>
    <%end%>

    <div class="form-group row">
        <div class="col-md-4">
            <%= f.label "Name", class:"control-label" %>
            <%= f.text_field :name, autofocus: true, class:"form-control", required: "required" %>
        </div>

        <div class="col-md-4">
            <%= f.label "Category", class:"control-label" %>
            <%#= f.text_field :category_name, data: {autocomplete_source: Category.order(:name).map(&:name)}, class:"form-control", required: "required" %>
            <%#= f.text_field :category_id, type: "hidden" %>
            <% if @product.category_id != nil && @product.category != nil %>
            <%= f.text_field :category_id, type: "hidden" %>
            <%= f.text_field :category_id, value: "#{category_name}", id: "category_name", name: "category_name", class:"form-control", required: "required" %>
            <% elsif %>
            <%= f.text_field :category_id, class:"form-control", required: "required" %>
            <% end %>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-4">
            <%= f.label "Color", class:"control-label" %>
            <%= f.text_field :color, class:"form-control", required: "required" %>
        </div>

        <div class="col-md-2">
            <%= f.label "Size", class:"control-label" %>
            <%= f.text_field :size, class:"form-control", required: "required" %>
        </div>

        <div class="col-md-2">
            <%= f.label "Price", class:"control-label" %>
            <%= f.text_field :price, class:"form-control", required: "required" %>
        </div>
    </div>

    <% if @stores.count > 0 %>
    <div class="form-group row">
        <label>Stores</label>
        <div class="container border bg-light">
            <div class="form-group row">
                <% @stores.each do |store| %>
                <div class="col-md-4 p-2">
                    <% if @store_product != nil %>
                        <% store_checked = "false" %>
                        <% @store_product.each do |sp| %>
                            <% if store.id == sp.store_id %>
                                <% store_checked = "true" %>
                            <% end %>
                        <% end %>

                        <% if store_checked == "true" %>
                            <%= check_box_tag "stores[]", store.id, checked: true %> <%= store.name %>
                        <% elsif %>
                            <%= check_box_tag "stores[]", store.id %> <%= store.name %>
                        <% end %>
                    <% elsif %>
                        <%= check_box_tag "stores[]", store.id %> <%= store.name %>
                    <% end %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>

    <div class="padding_top25">
        <%= f.submit "Save", class:"btn btn-success" %>
        <%= link_to "Back", products_path, class:"btn btn-outline-primary" %>
    </div>
<%end%>

app/views/products/edit.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <%= render "form", name:"Edit" %>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <%= render "partials/table_title", entity_label: "Products", button_label: "Product" %>
            
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <% @products.each do |product| %>
                    <tr>
                        <td>
                            <%= product.name %>
                        </td>
                        <td>
                            <% if product.category != nil %>
                            <%= product.category.name %>
                            <% end %>
                        </td>
                        <td>
                            <%#= link_to 'Show', product, class:"btn btn-success" %>
                            <%= link_to edit_product_path(product), class:"btn btn-success" do %>
                                <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
                                </svg> %>
                                Edit
                            <% end %>
                            <%= link_to product, method: :delete, class: "btn btn-outline-danger", remote: true, data: { confirm: 'Are you sure you want to delete this product?' } do %>
                                <%# <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                    <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                                </svg> %>
                                Delete
                            <% end %>
                            <%#= link_to "Edit", edit_product_path(product), class:"btn btn-success" %>
                            <%#= link_to "Delete", product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-success" %>
                        </td>
                    </tr>
                <%end%>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="container-xl">
    <div class="table-responsive">
        <div class="table-wrapper">
            <%= render "form", name:"Add" %>
        </div>
    </div>
</div>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', new_product_path %>